<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>parent</artifactId>
        <groupId>ru.sber.transport.corporate</groupId>
        <version>5.15</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>application</artifactId>
    <version>5.15</version>

    <name>Corporate application</name>
    <description>Corporate registration service</description>

    <properties>
        <server.port>8007</server.port>
        <openapi.url>https://apistudio.sigma.sbrf.ru/public/bundle/yml/e0c07c9b-0620-48be-a72b-03555e4a4fbb</openapi.url>
        <openapi.title>corporate</openapi.title>
        <java.version>21</java.version>
        <maven.compiler.source>21</maven.compiler.source>
    </properties>

    <dependencies>

        <!-- Spring -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.corporate</groupId>
            <artifactId>web</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-observation</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>role-check-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.corporate</groupId>
            <artifactId>messaging</artifactId>
            <version>5.10</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.user_data_confirmation</groupId>
            <artifactId>messaging</artifactId>
            <version>4.9</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.geo</groupId>
            <artifactId>grpc</artifactId>
            <version>3.20</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.grpc</groupId>
            <artifactId>server</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>properties-loader</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.service-discovery</groupId>
            <artifactId>starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-client</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>extended-rest-template</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>audit</artifactId>
        </dependency>

        <!-- Utils -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>authorization</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>file-works</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context-indexer</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-vault-config</artifactId>
        </dependency>

        <!-- Exchange -->
        <dependency>
            <groupId>ru.sber.transport.files</groupId>
            <artifactId>starter</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.grpc</groupId>
            <artifactId>client</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.geo-zones</groupId>
            <artifactId>messaging</artifactId>
            <version>3.20</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.roles</groupId>
            <artifactId>messaging</artifactId>
            <version>3.20</version>
        </dependency>

        <!-- Project -->
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>transport-core</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>human-readable-generator</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>documentation-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>enums</artifactId>
            <version>250127-1</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.scim</groupId>
            <artifactId>messaging</artifactId>
            <version>3.20</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>scripting</artifactId>
        </dependency>
        <dependency>
            <groupId>io.hypersistence</groupId>
            <artifactId>hypersistence-utils-hibernate-63</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.corporate</groupId>
            <artifactId>model</artifactId>
            <version>${project.parent.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.corporate</groupId>
            <artifactId>messages</artifactId>
            <version>${project.parent.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.corporate</groupId>
            <artifactId>providers-database</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>embedded-postgres</artifactId>
            <version>4.10</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.grpc</groupId>
            <artifactId>test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-test-binder</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>corporate</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>1.6.0</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <dependency>
                            <groupId>org.hibernate</groupId>
                            <artifactId>hibernate-jpamodelgen-jakarta</artifactId>
                            <version>5.6.15.Final</version>
                        </dependency>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <compilerArg>-Amapstruct.defaultComponentModel=spring</compilerArg>
                        <compilerArg>-Amapstruct.defaultInjectionStrategy=constructor</compilerArg>
                        <compilerArg>-Amapstruct.verbose=true</compilerArg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>io.github.ascopes</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>