spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/transport
        hikari:
            schema: ${spring.application.name}
            maximum-pool-size:  3
    jpa:
        properties:
            hibernate:
                default_schema: ${spring.application.name}
                generate_statistics: ${HIBERNATE_GENERATE_STATISTICS:false}
        hibernate:
            ddl-auto: validate
        show-sql: ${SHOW_SQL:false}
        open-in-view: false
    liquibase:
        change-log: classpath:db/changelog-master.yml
        url: ${spring.datasource.url}
        user: ${spring.datasource.username}
        password: ${spring.datasource.password}
        database-change-log-table: changelog_${spring.application.name}
        database-change-log-lock-table: changelog_${spring.application.name}_lock
        liquibase-schema: ${MIGRATIONS_SCHEMA:public}