package ru.sberbank.ditsib.transport.limits.constants;

public enum SettingsNames {
    EMP_LIMIT_REMAINS_TARGET,
    DEP_LIMIT_REMAINS_TARGET,
    
    EMP_LIMIT_GREEN_FROM,
    EMP_LIMIT_GREEN_UNTIL,
    EMP_LIMIT_YELLOW_FROM,
    EMP_LIMIT_YELLOW_UNTIL,
    EMP_LIMIT_RED_FROM,
    EMP_LIMIT_RED_UNTIL,
    
    DEP_LIMIT_GREEN_FROM,
    DEP_LIMIT_GREEN_UNTIL,
    DEP_LIMIT_YELLOW_FROM,
    DEP_LIMIT_YELLOW_UNTIL,
    DEP_LIMIT_RED_FROM,
    DEP_LIMIT_RED_UNTIL
}
