syntax = "proto3";

package ru.sber.transport.corporate.sync_import.grpc.service;

import "google/protobuf/struct.proto";

/*
 * Сервис для синхронизации оргштатной структуры
 */
service SyncService {

  /*
   * Синхронизация должностей
   *
   * param - данные для сохранения
   * returns - сохраненные данные
   */
  rpc SyncPosition(stream PositionRequest) returns (stream SyncResponse);

  /*
   * Синхронизация подразделений
   *
   * param - данные для сохранения
   * returns - сохраненные данные
   */
  rpc SyncDepartment(stream DepartmentRequest) returns (stream SyncResponse);

  /*
   * Синхронизация сотрудников
   *
   * param - данные для сохранения
   * returns - сохраненные данные
   */
  rpc SyncEmployee(stream EmployeeRequest) returns (stream SyncResponse);

}

/*
 * Должность
 */
message PositionRequest {

  /*
   * Идентификатор
   */
  NullableString id = 1;

  /*
   * Название
   */
  string name = 2;

  /*
   * Признак того, что согласование не требуется
   */
  bool noApproveRequired = 3;

  /*
   * Идентификатор организации
   */
  string organizationId = 4;

  /*
   * Идентификатор синхронизации
   */
  string syncId = 5;

  /*
   * Статус активности
   */
  Active status = 6;

}

/*
 * Подразделение
 */
message DepartmentRequest {

  /*
   * Идентификатор
   */
  NullableString id = 1;

  /*
   * Код
   */
  string code = 2;

  /*
   * Название
   */
  string name = 3;

  /*
   * Местоположение
   */
  NullableString location = 4;

  /*
   * Руководитель
   */
  NullableString head = 5;

  /*
   * Идентификатор организации
   */
  string organizationId = 6;

  /*
   * Родительское подразделение
   */
  NullableString parentId = 7;

  /*
   * Статус активности
   */
  Active status = 8;

  /*
   * Код уровня
   */
  NullableInt levelCode = 9;

  /*
   * Название уровня
   */
  NullableString levelName = 10;

  /*
   * Идентификатор организации
   */
  string syncId = 11;

}

/*
 * Сотрудник
 */
message EmployeeRequest {

  /*
   * Идентификатор
   */
  NullableString id = 1;

  /*
   * Адрес электронной почты
   */
  NullableString email = 2;

  /*
   * Имя
   */
  string firstName = 3;

  /*
   * Фамилия
   */
  string lastName = 4;

  /*
   * Номер мобильного
   */
  NullableString mobilePhone = 5;

  /*
   * Отчество
   */
  NullableString patronymic = 6;

  /*
   * Табельный номер
   */
  string personnelNumber = 7;

  /*
   * Идентификатор подразделения
   */
  string departmentId = 8;

  /*
   * Идентификатор должности
   */
  string positionId = 9;

  /*
   * Идентификатор руководителя
   */
  NullableString supervisorId = 10;

  /*
   * Статус активности
   */
  Active status = 11;

  /*
   * Пол
   */
  Gender gender = 12;

  /*
   * Дата увольнения
   */
  NullableDate fireDate = 13;

  /*
   * Внешний адрес электронной почты
   */
  NullableString externalEmail = 14;

  /*
   * Комната
   */
  NullableString room = 15;

  /*
   * Согласие ПДн
   */
  bool consent = 16;

  /*
   * МВЗ
   */
  NullableString costCenter = 17;

  /*
   * Разъездной характер работы
   */
  Itinerant itinerant = 18;

  /*
   * Свидетельство о браке
   */
  NullableString marriageCertificate = 19;

  /*
   * Идентификатор организации
   */
  string organizationId = 20;

}

/*
 * Ответ с данными
 */
message SyncResponse {

  /*
   * Идентификатор объекта
   */
  string id = 1;

  /*
   * Идентификатор синхронизации
   */
  string syncId = 2;

}

/*
 * Обнуляемая строка
 */
message NullableString {
  oneof Kind {
    google.protobuf.NullValue null = 1;
    string value = 2;
  }
}

/*
 * Обнуляемое число
 */
message NullableInt {
  oneof Kind {
    google.protobuf.NullValue null = 1;
    int32 value = 2;
  }
}

/**
 * Обнуляемая дата
 */
message NullableDate {
  oneof Kind {
    google.protobuf.NullValue null = 1;
    Date value = 2;
  }
}

/*
 * Дата
 */
message Date {

  /*
   * Год
   */
  uint32 year = 1;

  /*
   * Месяц
   */
  uint32 month = 2;

  /*
   * День
   */
  uint32 day = 3;
}

/*
 * Признак активности
 */
enum Active {

  /*
   * Активен
   */
  ACTIVE = 0;

  /*
   * Не активен
   */
  INACTIVE = 1;
}

/*
 * Пол
 */
enum Gender {

  /*
   * Мужской
   */
  MALE = 0;

  /*
   * Женский
   */
  FEMALE = 1;
}

/*
 * Разъездной характер работы
 */
enum Itinerant {

  /*
   * Нет
   */
  NONE = 0;

  /*
   * Частичный
   */
  PARTIAL = 1;

  /*
   * Полный
   */
  FULL = 2;
}