kind: Deployment
apiVersion: apps/v1
metadata:
  name: limits
  namespace: ci02351878-edevgen-sbertransport-dev
  labels:
    app: limits
    app.kubernetes.io/name: limits
    app.kubernetes.io/part-of: transport
    date_build: 05_22_2023_154709
    distrib: Bugfix-TRANSPORT-13725-g-13
    repo: as-sbertransport
    template: limits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limits
  template:
    metadata:
      labels:
        app: limits
        app.kubernetes.io/name: limits
        app.kubernetes.io/part-of: transport
      annotations:
        sidecar.istio.io/inject: 'true'
        traffic.sidecar.istio.io/excludeOutboundPorts: '6565'
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    spec:
      restartPolicy: Always
      serviceAccountName: springboot-servicediscovery
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 4G
            requests:
              cpu: '1'
              memory: 2G
          terminationMessagePath: /dev/termination-log
          name: limits
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: kafka
                  key: brokers
            - name: DEADLINE_CHECK_PERIOD_CRON_LIMITS
              valueFrom:
                configMapKeyRef:
                  name: limits
                  key: deadline.check.period
            - name: JDK_JAVA_OPTIONS
              value: >-
                -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9001
            - name: SPRING_PROFILES_INCLUDE
              value: secman
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - name: http-limits
              containerPort: 8009
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /mnt
            - name: logs
              mountPath: /log
            - name: temp
              mountPath: /tmp
            - name: kubernetes
              mountPath: /app/resources/application-kubernetes.yml
              subPath: application-kubernetes.yml
            - name: logging
              mountPath: /app/resources/application-logging.yml
              subPath: application-logging.yml
            - name: secman
              mountPath: /app/resources/application-secman.yml
              subPath: application-secman.yml
          terminationMessagePolicy: FallbackToLogsOnError
          image: >-
            registry.sigma.sbrf.ru/dev/ci02351878/ci02353146_transport_dev/transport/limits:230818-1-17898164
      volumes:
        - name: data
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: temp
          emptyDir: {}
        - name: kubernetes
          configMap:
            name: kubernetes
            defaultMode: 420
        - name: logging
          configMap:
            name: logging
            defaultMode: 420
        - name: secman-avro
          configMap:
            name: secman
            defaultMode: 420
            optional: true