application: corporate
repo: app_platform_corporate
resources:
  limits:
    cpu: '1'
    memory: 2G
  requests:
    cpu: '1'
    memory: 2G
port:
  http:
    number: 8007
    name: corporate
    target: 8080
  grpc:
    number: 6565
    name: corporate
    target: 6565
routing:
  match:
    prefix: /api/organizations
  rewrite:
    uri: ' '
secman:
  type: built_in
profiles: kafka
additional:
  envs:
    - name: SPRING_CLOUD_CONFIG_URI
      value: http://http-config-server:8080
    - name: ORGANIZATION_LOGO_ALLOWED_TYPES
      valueFrom:
        configMapKeyRef:
          name: files
          key: image.allowed
    - name: ADDRESSES_HOST
      value: 'http://http-address:8080'
  configMap:
    - name: kafka-secman
      data:
        application-kafka-ssl.yml: |-
          spring:
            cloud:
              vault:
                namespace: CI02351878_CI02671580
                authentication: kubernetes
                kubernetes:
                  role: ci02351878-edevgen-sbertransport-dev
                  kubernetes-path: os/dev-terra000003-ids.ocp.delta.sbrf.ru
                enabled: true
                port: 443
                host: t.secrets.delta.sbrf.ru
            config:
              import: 
                - optional:vault://A/TRANSP/OSH/MAIN/KV/ci02351878-edevgen-sbertransport-dev/application,kafka-ssl
        application-kafka-avro.yml: |-
          spring:
            cloud:
              vault:
                namespace: CI02351878_CI02671580
                authentication: kubernetes
                kubernetes:
                  role: ci02351878-edevgen-sbertransport-dev
                  kubernetes-path: os/dev-terra000003-ids.ocp.delta.sbrf.ru
                enabled: true
                port: 443
                host: t.secrets.delta.sbrf.ru
            config:
              import: 
                - optional:vault://A/TRANSP/OSH/MAIN/KV/ci02351878-edevgen-sbertransport-dev/application,kafka-avro
  volumes:
    - name: kafka-secman
      configMap:
        name: kafka-secman
        defaultMode: 420
  mounts:
    - name: kafka-secman
      mountPath: /app/resources/application-kafka-ssl.yml
      subPath: application-kafka-ssl.yml
    - name: kafka-secman
      mountPath: /app/resources/application-kafka-avro.yml
      subPath: application-kafka-avro.yml